### ISSUE TITLE
Space leader key not working

### ISSUE THREAD

**Issue by alexbrillant** [nasim80/SUCH-Vim#16]
La variable leaderkey a disparu. 
La leaderkey étais un espace.
tous les commandes qui faisait `<Leader> `avant ne fonctionne plus.

**Comment by nathanielsimard** [comment]
Je l'ai enlevé des configs par défault, tu dois défénir ta propre leader dans ton .suchvimrc.

**Comment by WhippetsAintDogs** [comment]
Oui, mais on devrait l'écrire dans le Readme
#DefineYourLeaderKey with : ...
in .suchvimrc :P
